import Testing
import Utilities
@testable import AdventOfCode2025

struct Day7Tests {
    let day = Day7()
    
    let input: Input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    
    @Test func part1() {
        #expect(day.part1Solution(for: input) == 21)
        #expect(day.part1Solution() == 1507)
    }
    
    @Test func part2() {
        #expect(day.part2Solution(for: input) == 40)
        #expect(day.part2Solution() == 1537373473728)
    }
}
